import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { UserProvider } from "./context/userContext";
import { CartProvider } from "./context/cartContext";
import { WishProvider } from "./context/wishContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <UserProvider>
            <CartProvider>
              <WishProvider>
                <Navbar />
                <main className="flex flex-grow justify-center">
                  {children}
                </main>
                <Footer />
              </WishProvider>
            </CartProvider>
          </UserProvider>
        </div>
      </body>
    </html>
  );
}
